# ============================================================
# 00_audit_raw_dictionary.R
# Auditoría estructural raw del RCBPA Arequipa 2015-2022
# - lectura conservadora del Excel
# - diccionario por hoja
# - perfil de calidad
# - crosswalk estructural
# - mapeo preliminar IARC
# - decision log
# - audit log machine-readable
# ============================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(stringr)
  library(janitor)
  library(readr)
  library(tibble)
  library(jsonlite)
  library(lubridate)
  library(glue)
  library(here)
})

# ------------------------------------------------------------
# 1) setup
# ------------------------------------------------------------
path_xlsx <- here("DATA", "RAW", "RCBPAQP 2015-2022.xlsx")

dir.create(here("DATA", "DERIVED"), recursive = TRUE, showWarnings = FALSE)
dir.create(here("REPORTS"), recursive = TRUE, showWarnings = FALSE)

out_raw_exact   <- here("DATA", "DERIVED", "rcpa_raw_exact.rds")
out_raw_tagged  <- here("DATA", "DERIVED", "rcpa_raw_tagged.rds")

out_dict_sheet  <- here("REPORTS", "data_dictionary_by_sheet.csv")
out_var_quality <- here("REPORTS", "variable_quality_profile.csv")
out_presence    <- here("REPORTS", "variable_presence_by_year.csv")
out_crosswalk   <- here("REPORTS", "data_dictionary_crosswalk.csv")
out_decisionlog <- here("REPORTS", "data_dictionary_decision_log.csv")
out_audit_json  <- here("REPORTS", "data_audit_log.json")

out_annex_structure <- here("REPORTS", "annex_dataset_structure.csv")
out_annex_dict      <- here("REPORTS", "annex_variable_dictionary.csv")
out_annex_presence  <- here("REPORTS", "annex_variable_presence_matrix.csv")
out_harmonized      <- here("DATA", "DERIVED", "rcpa_harmonized_long.rds")
out_harmonized_counts <- here("REPORTS", "harmonized_variable_counts.csv")
out_harmonized_codebook <- here("REPORTS", "harmonized_domain_profile.csv")

run_date <- as.character(Sys.Date())

# ------------------------------------------------------------
# 2) helpers
# ------------------------------------------------------------
safe_parse_year <- function(x) {
  y <- suppressWarnings(readr::parse_number(as.character(x)))
  ifelse(is.na(y), NA_real_, y)
}

clean_name_conservative <- function(x) {
  x %>%
    as.character() %>%
    str_trim() %>%
    str_replace_all("\\s+", "_") %>%
    str_replace_all("[°º]+", "") %>%
    str_replace_all("#", "number") %>%
    str_replace_all("[^A-Za-z0-9_]+", "_") %>%
    str_replace_all("_+", "_") %>%
    str_replace_all("^_|_$", "") %>%
    str_to_lower()
}

guess_type_raw <- function(x) {
  x_chr <- as.character(x)
  x_chr <- str_trim(x_chr)
  x_chr[x_chr == ""] <- NA_character_
  
  nonmiss <- x_chr[!is.na(x_chr)]
  if (length(nonmiss) == 0) return("all_missing")
  
  p_num <- mean(str_detect(nonmiss, "^-?\\d+(\\.\\d+)?$"))
  p_date <- mean(str_detect(nonmiss, "^(\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}|\\d{4}[/-]\\d{1,2}[/-]\\d{1,2}|\\d{5})$"))
  p_int_like <- mean(str_detect(nonmiss, "^-?\\d+$"))
  
  if (p_date >= 0.7) return("date_like")
  if (p_int_like >= 0.9) return("integer_like")
  if (p_num >= 0.9) return("numeric_like")
  
  nunq <- dplyr::n_distinct(nonmiss)
  if (nunq <= 12) return("categorical_like")
  
  "character_like"
}

sample_examples <- function(x, n = 3) {
  vals <- x %>%
    as.character() %>%
    str_trim()
  
  vals[vals == ""] <- NA_character_
  
  out <- vals[!is.na(vals)] %>%
    unique()
  
  out <- head(out, n)
  length(out) <- n
  out
}

safe_min_chr <- function(x) {
  z <- x %>% as.character() %>% str_trim()
  z[z == ""] <- NA_character_
  z <- z[!is.na(z)]
  if (length(z) == 0) return(NA_character_)
  suppressWarnings(as.character(min(z)))
}

safe_max_chr <- function(x) {
  z <- x %>% as.character() %>% str_trim()
  z[z == ""] <- NA_character_
  z <- z[!is.na(z)]
  if (length(z) == 0) return(NA_character_)
  suppressWarnings(as.character(max(z)))
}

name_suspicious_flag <- function(raw_name) {
  nm <- as.character(raw_name)
  nm_trim <- str_trim(nm)
  
  is.na(nm) |
    nm_trim == "" |
    str_detect(nm, "^Unnamed") |
    str_detect(nm, "^\\.\\.\\.") |
    str_detect(nm, "^X\\d+$") |
    str_detect(nm, "^[0-9]+$") |
    str_detect(nm, "^__blank_col_")
}

header_anomaly_class <- function(raw_name) {
  nm <- as.character(raw_name)
  case_when(
    is.na(nm) ~ "missing_name",
    str_trim(nm) == "" ~ "blank_name",
    str_detect(nm, "^__blank_col_") ~ "blank_header_repaired",
    str_detect(nm, "^[0-9]+$") ~ "numeric_header",
    str_detect(nm, "^Unnamed") ~ "unnamed_header",
    str_detect(nm, "^X\\d+$") ~ "autogenerated_header",
    TRUE ~ "none"
  )
}

possible_iarc_from_name <- function(x) {
  nm <- clean_name_conservative(x)
  
  case_when(
    str_detect(nm, "sexo|sex") ~ "sexo",
    str_detect(nm, "^edad$|age") ~ "edad",
    str_detect(nm, "fecdiag|fecha_diag|diagn") ~ "fecha_diagnostico",
    str_detect(nm, "topo|topog|icdo_top") ~ "topografia_icdo",
    str_detect(nm, "morf|hist|morph") ~ "morfologia_icdo",
    str_detect(nm, "comport|behav") ~ "comportamiento",
    str_detect(nm, "grado|grade") ~ "grado",
    str_detect(nm, "lateral|late") ~ "lateralidad",
    str_detect(nm, "base|basis") ~ "base_diagnostico",
    str_detect(nm, "estvit|vital") ~ "estado_vital",
    str_detect(nm, "fecdef|fecha_def|death") ~ "fecha_muerte",
    str_detect(nm, "fuc|ultimo_contact|last_contact") ~ "fecha_ultimo_contacto",
    str_detect(nm, "res|resid|deptres|provdist|domic") ~ "residencia",
    str_detect(nm, "pmseq|pmtot|multiple|primar") ~ "multiple_primary",
    TRUE ~ NA_character_
  )
}

confidence_from_name <- function(x) {
  nm <- clean_name_conservative(x)
  
  case_when(
    nm %in% c("sexo", "edad", "fecdiag", "topo", "morf", "grado", "fuc", "estvit", "fecdef") ~ "high",
    str_detect(nm, "base|lateral|comport|deptres|provdist|res|pmseq|pmtot") ~ "moderate",
    TRUE ~ "low"
  )
}

classify_variable_role <- function(clean_name, raw_name = NA_character_, possible_iarc_field = NA_character_) {
  nm <- clean_name_conservative(clean_name)
  raw_nm <- clean_name_conservative(raw_name)
  
  case_when(
    !is.na(possible_iarc_field) ~ "epidemiologic_core",
    str_detect(nm, "^tumourid$|^patientid|recordid|nodoc|hc$|numpat|tumouridsourcetable|sourcerecordid") ~ "identifier",
    str_detect(nm, "updatedby|updatedate|recordstatus|checkstatus|obsoleteflag|unduplicationstatus") ~ "administrative",
    str_detect(nm, "notif|inst_number11|tipoest|prof|veri|estcas|modif|busc|caso|obs") ~ "administrative",
    str_detect(nm, "^1_ape$|^2_ape$|^1_nombre$|^2_nombre$|^3_nombre$|pais|estciv|ocu|instr|tipo") ~ "person_descriptive",
    str_detect(nm, "^cie10$|^cicn$|^estadio$|^tx$|^nx$|^mx$|^dx$|^causa$") ~ "clinical_auxiliary",
    str_detect(nm, "blank_col|^[0-9]+$") | raw_nm %in% c("blank_col_2", "673668") ~ "structural_anomaly",
    TRUE ~ "other"
  )
}

is_structural_garbage <- function(clean_name, header_anomaly, flag_all_missing) {
  clean_name %in% c("blank_col_2", "673668") |
    header_anomaly != "none" |
    flag_all_missing
}

is_candidate_for_indicator_qc <- function(canonical_candidate, possible_iarc_field, clean_name) {
  canonical_nm <- coalesce(canonical_candidate, "")
  iarc_nm <- coalesce(possible_iarc_field, "")
  clean_nm <- coalesce(clean_name, "")
  
  canonical_nm %in% c(
    "sexo", "edad", "fecha_diagnostico", "topografia_icdo", "morfologia_icdo",
    "comportamiento", "grado", "base_diagnostico", "estado_vital",
    "fecha_muerte", "fecha_ultimo_contacto", "lateralidad",
    "residencia__res", "residencia__deptres", "residencia__provdist",
    "multiple_primary__pmseq", "multiple_primary__pmtot", "multiple_primary__pmcod",
    "causa", "cie10"
  ) |
    iarc_nm %in% c(
      "sexo", "edad", "fecha_diagnostico", "topografia_icdo", "morfologia_icdo",
      "comportamiento", "grado", "base_diagnostico", "estado_vital",
      "fecha_muerte", "fecha_ultimo_contacto", "lateralidad", "residencia", "multiple_primary"
    ) |
    clean_nm %in% c("causa", "cie10")
}

domain_signature <- function(x, max_n = 20) {
  vals <- x %>%
    as.character() %>%
    str_trim()
  
  vals[vals == ""] <- NA_character_
  vals <- vals[!is.na(vals)]
  
  if (length(vals) == 0) return("all_missing")
  
  nunq <- dplyr::n_distinct(vals)
  
  if (nunq <= max_n) {
    sig <- vals %>%
      unique() %>%
      sort() %>%
      paste(collapse = " | ")
    return(sig)
  }
  
  paste0("high_cardinality_n=", nunq)
}

norm_adist <- function(a, b) {
  a <- as.character(a)
  b <- as.character(b)
  if (is.na(a) || is.na(b) || (a == "" && b == "")) return(0)
  d <- utils::adist(a, b)[1]
  m <- max(nchar(a), nchar(b))
  if (m == 0) return(0)
  as.numeric(d / m)
}

score_name_similarity <- function(a, b) {
  1 - norm_adist(clean_name_conservative(a), clean_name_conservative(b))
}

score_domain_similarity <- function(a, b) {
  if (is.na(a) || is.na(b)) return(0)
  if (a == b) return(1)
  if (str_detect(a, "^high_cardinality") && str_detect(b, "^high_cardinality")) return(0.5)
  0
}

score_position_similarity <- function(pos_a, pos_b, max_pos_diff = 10) {
  if (is.na(pos_a) || is.na(pos_b)) return(0)
  d <- abs(pos_a - pos_b)
  pmax(0, 1 - d / max_pos_diff)
}

evidence_class <- function(score) {
  case_when(
    score >= 0.85 ~ "evidence_direct",
    score >= 0.65 ~ "inference_probable",
    score >= 0.45 ~ "hypothesis_uncertain",
    TRUE ~ "weak_signal"
  )
}

confidence_class <- function(score) {
  case_when(
    score >= 0.85 ~ "high",
    score >= 0.65 ~ "moderate",
    score >= 0.45 ~ "low",
    TRUE ~ "unknown"
  )
}

# ------------------------------------------------------------
# 3) lectura del Excel
# ------------------------------------------------------------
sheets <- readxl::excel_sheets(path_xlsx)

# ------------------------------------------------------------
# 4) creación de raw_sheets
#    Nota: algunas hojas pueden traer nombres NA o vacíos.
#    Para poder operar con dplyr sin perder trazabilidad,
#    se crean nombres técnicos mínimos y reversibles.
# ------------------------------------------------------------
repair_raw_colnames <- function(nms) {
  nms_chr <- as.character(nms)
  nms_chr[is.na(nms_chr)] <- ""
  nms_chr <- str_trim(nms_chr)
  
  nms_fixed <- if_else(
    nms_chr == "",
    paste0("__blank_col_", seq_along(nms_chr)),
    nms_chr
  )
  
  make.unique(nms_fixed, sep = "__dup")
}

raw_sheets <- set_names(
  map(sheets, function(sh) {
    df <- readxl::read_excel(
      path = path_xlsx,
      sheet = sh,
      col_types = "text",
      .name_repair = "minimal"
    ) %>%
      as_tibble(.name_repair = "minimal")
    
    names(df) <- repair_raw_colnames(names(df))
    df
  }),
  sheets
)

# ------------------------------------------------------------
# 5) construcción de raw_exact
# ------------------------------------------------------------
raw_exact_list <- imap(raw_sheets, function(df, sh) {
  names_raw <- names(df)
  
  df %>%
    mutate(
      sheet_source = sh,
      year_sheet = safe_parse_year(sh),
      .before = 1
    ) %>%
    setNames(c("sheet_source", "year_sheet", names_raw))
})

raw_exact <- bind_rows(raw_exact_list)

saveRDS(raw_exact, out_raw_exact)

# ------------------------------------------------------------
# 6) construcción de raw_tagged
#    Nota: NO colapsa ambigüedades.
#    Se guarda como lista con:
#    - data: bind_rows con audit names únicos
#    - column_map: mapa sheet/raw_name/clean_name/audit_name
# ------------------------------------------------------------
tagged_sheet_objects <- imap(raw_sheets, function(df, sh) {
  raw_names <- names(df)
  
  colmap <- tibble(
    sheet = sh,
    year_sheet = safe_parse_year(sh),
    col_position = seq_along(raw_names),
    raw_name = raw_names,
    clean_name = clean_name_conservative(raw_names),
    possible_iarc_field = map_chr(raw_names, ~ coalesce(possible_iarc_from_name(.x), NA_character_)),
    confidence_iarc_mapping = map_chr(raw_names, confidence_from_name)
  ) %>%
    group_by(sheet) %>%
    mutate(
      clean_name_unique_within_sheet = make.unique(clean_name, sep = "__dup"),
      audit_name = paste0(clean_name_unique_within_sheet, "__", str_pad(col_position, 2, pad = "0"))
    ) %>%
    ungroup()
  
  df2 <- df
  names(df2) <- colmap$audit_name
  
  df2 <- df2 %>%
    mutate(
      sheet_source = sh,
      year_sheet = safe_parse_year(sh),
      .before = 1
    )
  
  list(data = df2, column_map = colmap)
})

raw_tagged_data <- map(tagged_sheet_objects, "data") %>% bind_rows()
raw_tagged_colmap <- map(tagged_sheet_objects, "column_map") %>% bind_rows()

raw_tagged <- list(
  data = raw_tagged_data,
  column_map = raw_tagged_colmap,
  created_at = Sys.time(),
  source_file = path_xlsx
)

saveRDS(raw_tagged, out_raw_tagged)

# ------------------------------------------------------------
# 7) perfil de variables + diccionario por hoja
# ------------------------------------------------------------
data_dictionary_by_sheet <- imap_dfr(raw_sheets, function(df, sh) {
  raw_names <- names(df)
  year_val <- safe_parse_year(sh)
  
  map_dfr(seq_along(raw_names), function(i) {
    nm <- raw_names[i]
    x <- df[[i]]
    x_chr <- as.character(x)
    x_trim <- str_trim(x_chr)
    x_trim[x_trim == ""] <- NA_character_
    
    ex <- sample_examples(x_trim, n = 3)
    clean_name <- clean_name_conservative(nm)
    header_anomaly <- header_anomaly_class(nm)
    
    tibble(
      sheet = sh,
      year_sheet = year_val,
      col_position = i,
      raw_name = nm,
      clean_name = clean_name,
      raw_type_guess = guess_type_raw(x_trim),
      n_rows = nrow(df),
      n_non_missing = sum(!is.na(x_trim)),
      pct_missing = round(mean(is.na(x_trim)) * 100, 2),
      n_unique = dplyr::n_distinct(x_trim, na.rm = TRUE),
      example_value_1 = ex[1],
      example_value_2 = ex[2],
      example_value_3 = ex[3],
      min_value = safe_min_chr(x_trim),
      max_value = safe_max_chr(x_trim),
      domain_signature = domain_signature(x_trim),
      possible_meaning = case_when(
        str_detect(clean_name, "sexo|sex") ~ "Posible sexo",
        str_detect(clean_name, "^edad$|age") ~ "Posible edad",
        str_detect(clean_name, "fecdiag|diagn") ~ "Posible fecha de diagnóstico",
        str_detect(clean_name, "topo") ~ "Posible topografía ICD-O",
        str_detect(clean_name, "morf") ~ "Posible morfología ICD-O",
        str_detect(clean_name, "base") ~ "Posible base de diagnóstico",
        str_detect(clean_name, "lateral|late") ~ "Posible lateralidad",
        str_detect(clean_name, "res|deptres|provdist") ~ "Posible residencia",
        str_detect(clean_name, "estvit") ~ "Posible estado vital",
        str_detect(clean_name, "fecdef") ~ "Posible fecha de defunción",
        str_detect(clean_name, "fuc") ~ "Posible fecha de último contacto",
        TRUE ~ NA_character_
      ),
      possible_iarc_field = possible_iarc_from_name(nm),
      confidence_iarc_mapping = confidence_from_name(nm),
      header_anomaly = header_anomaly,
      notes = case_when(
        header_anomaly != "none" ~ paste0("Encabezado anómalo: ", header_anomaly, "; revisar estructura original de la hoja."),
        round(mean(is.na(x_trim)) * 100, 2) == 100 ~ "Columna completamente vacía.",
        dplyr::n_distinct(x_trim, na.rm = TRUE) <= 1 & sum(!is.na(x_trim)) > 0 ~ "Columna constante.",
        TRUE ~ NA_character_
      )
    )
  })
})

write_csv(data_dictionary_by_sheet, out_dict_sheet, na = "")

# ------------------------------------------------------------
# 8) perfil de calidad de variables
# ------------------------------------------------------------
variable_quality_profile <- data_dictionary_by_sheet %>%
  mutate(
    flag_all_missing = pct_missing == 100,
    flag_near_empty = pct_missing >= 95 & pct_missing < 100,
    flag_name_suspicious = name_suspicious_flag(raw_name),
    flag_header_anomaly = header_anomaly != "none",
    flag_constant = n_unique <= 1 & n_non_missing > 0,
    flag_high_cardinality_text = raw_type_guess == "character_like" & n_unique > pmax(50, n_rows * 0.5),
    flag_domain_strange = case_when(
      raw_type_guess == "integer_like" & str_detect(raw_name, regex("sexo|sex", ignore_case = TRUE)) &
        !str_detect(paste(example_value_1, example_value_2, example_value_3), "^[12MFmfHh]") ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>%
  group_by(sheet) %>%
  mutate(
    flag_duplicate_clean_name_within_sheet = duplicated(clean_name) | duplicated(clean_name, fromLast = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    variable_role = classify_variable_role(clean_name, raw_name, possible_iarc_field),
    flag_structural_garbage = is_structural_garbage(clean_name, header_anomaly, flag_all_missing),
    candidate_for_indicator_qc = is_candidate_for_indicator_qc(NA_character_, possible_iarc_field, clean_name),
    quality_issue_summary = pmap_chr(
      list(
        flag_all_missing,
        flag_near_empty,
        flag_name_suspicious,
        flag_header_anomaly,
        flag_constant,
        flag_high_cardinality_text,
        flag_domain_strange,
        flag_duplicate_clean_name_within_sheet,
        flag_structural_garbage
      ),
      function(a, b, c, d, e, f, g, h, i) {
        issues <- c()
        if (isTRUE(a)) issues <- c(issues, "all_missing")
        if (isTRUE(b)) issues <- c(issues, "near_empty")
        if (isTRUE(c)) issues <- c(issues, "name_suspicious")
        if (isTRUE(d)) issues <- c(issues, "header_anomaly")
        if (isTRUE(e)) issues <- c(issues, "constant")
        if (isTRUE(f)) issues <- c(issues, "high_cardinality_text")
        if (isTRUE(g)) issues <- c(issues, "domain_strange")
        if (isTRUE(h)) issues <- c(issues, "duplicate_clean_name_within_sheet")
        if (isTRUE(i)) issues <- c(issues, "structural_garbage")
        if (length(issues) == 0) "none" else paste(issues, collapse = "; ")
      }
    )
  ) %>%
  select(
    sheet, year_sheet, col_position, raw_name, clean_name, raw_type_guess,
    n_rows, n_non_missing, pct_missing, n_unique,
    header_anomaly, variable_role, candidate_for_indicator_qc,
    possible_iarc_field, confidence_iarc_mapping,
    starts_with("flag_"), quality_issue_summary
  )

write_csv(variable_quality_profile, out_var_quality, na = "")

# ------------------------------------------------------------
# 9) presencia de variables por año
# ------------------------------------------------------------
presence_long <- data_dictionary_by_sheet %>%
  transmute(
    year_sheet,
    sheet,
    raw_name,
    clean_name,
    present = 1L
  )

variable_presence_by_year <- data_dictionary_by_sheet %>%
  group_by(clean_name) %>%
  summarise(
    raw_name_variants = paste(sort(unique(raw_name)), collapse = " | "),
    sheets_present = paste(sort(unique(sheet)), collapse = " | "),
    years_present = paste(sort(unique(year_sheet)), collapse = " | "),
    n_years_present = n_distinct(year_sheet),
    first_year_present = suppressWarnings(min(year_sheet, na.rm = TRUE)),
    last_year_present = suppressWarnings(max(year_sheet, na.rm = TRUE)),
    appears_all_years = n_years_present == n_distinct(data_dictionary_by_sheet$year_sheet),
    years_missing = paste(
      setdiff(sort(unique(data_dictionary_by_sheet$year_sheet)), sort(unique(year_sheet))),
      collapse = " | "
    ),
    consistency_structural = case_when(
      appears_all_years ~ "stable_all_years",
      n_years_present >= 6 ~ "mostly_stable",
      n_years_present >= 3 ~ "partially_stable",
      TRUE ~ "sporadic_or_year_specific"
    ),
    .groups = "drop"
  )

write_csv(variable_presence_by_year, out_presence, na = "")

# ------------------------------------------------------------
# 9b) disponibilidad de variables para indicadores de calidad epidemiológica
#     Aquí solo auditamos DISPONIBILIDAD ESTRUCTURAL, no calculamos todavía MV/DCO/etc.
# ------------------------------------------------------------
quality_indicator_field_availability <- tibble(
  indicator_family = c(
    "MV_histological_verification",
    "DCO_death_certificate_only",
    "PSU_primary_site_unknown",
    "Age_unknown",
    "Sex_unknown",
    "Basis_of_diagnosis_distribution",
    "Vital_status_followup"
  ),
  required_fields = c(
    "morfologia_icdo | base_diagnostico",
    "base_diagnostico | fecha_muerte | causa",
    "topografia_icdo",
    "edad",
    "sexo",
    "base_diagnostico",
    "estado_vital | fecha_muerte | fecha_ultimo_contacto"
  ),
  availability_status = c(
    "candidate_available",
    "candidate_available_but_needs_coding_review",
    "candidate_available",
    "candidate_available",
    "candidate_available",
    "candidate_available",
    "candidate_available"
  ),
  notes = c(
    "MV requerirá revisar la codificación local de BASE #7 y su relación con morfología.",
    "DCO requerirá confirmar si BASE #7 codifica certificado de defunción y si CAUSA/FECDEF son utilizables.",
    "PSU requerirá revisar códigos topográficos desconocidos o mal definidos.",
    "Debe verificarse cómo se codifica edad desconocida.",
    "Debe verificarse cómo se codifica sexo desconocido.",
    "Necesita tabla de frecuencias y diccionario de códigos locales de BASE #7.",
    "Permite evaluar completitud básica de seguimiento/vital status."
  )
)

write_csv(
  quality_indicator_field_availability,
  here("REPORTS", "quality_indicator_field_availability.csv"),
  na = ""
)

presence_matrix <- presence_long %>%
  distinct(clean_name, year_sheet, present) %>%
  pivot_wider(
    names_from = year_sheet,
    values_from = present,
    values_fill = 0
  ) %>%
  arrange(clean_name)

# ------------------------------------------------------------
# 10) detección de equivalencias
#    Cambio local importante:
#    el join cartesiano completo puede explotar en tiempo/memoria.
#    Aquí usamos bloqueo conservador para comparar solo pares plausibles.
# ------------------------------------------------------------
dict_pairs <- data_dictionary_by_sheet %>%
  select(
    sheet, year_sheet, col_position, raw_name, clean_name,
    raw_type_guess, domain_signature, n_unique,
    possible_iarc_field
  ) %>%
  mutate(
    clean_prefix = str_sub(clean_name, 1, 6),
    block_key = case_when(
      !is.na(possible_iarc_field) ~ paste0("iarc::", possible_iarc_field),
      TRUE ~ paste0("name::", clean_prefix, "::", raw_type_guess)
    )
  )

candidate_pairs <- dict_pairs %>%
  rename(
    sheet_a = sheet,
    year_a = year_sheet,
    pos_a = col_position,
    raw_name_a = raw_name,
    clean_name_a = clean_name,
    type_a = raw_type_guess,
    domain_a = domain_signature,
    n_unique_a = n_unique,
    iarc_a = possible_iarc_field,
    clean_prefix_a = clean_prefix,
    block_key = block_key
  ) %>%
  inner_join(
    dict_pairs %>%
      rename(
        sheet_b = sheet,
        year_b = year_sheet,
        pos_b = col_position,
        raw_name_b = raw_name,
        clean_name_b = clean_name,
        type_b = raw_type_guess,
        domain_b = domain_signature,
        n_unique_b = n_unique,
        iarc_b = possible_iarc_field,
        clean_prefix_b = clean_prefix,
        block_key = block_key
      ),
    by = "block_key"
  ) %>%
  filter(
    !(sheet_a == sheet_b & pos_a == pos_b),
    year_a <= year_b,
    !(year_a == year_b & pos_a >= pos_b)
  ) %>%
  filter(
    sheet_a != sheet_b |
      clean_name_a == clean_name_b |
      clean_prefix_a == clean_prefix_b |
      (!is.na(iarc_a) & !is.na(iarc_b) & iarc_a == iarc_b)
  )

equivalence_candidates <- candidate_pairs %>%
  mutate(
    score_raw_name = map2_dbl(raw_name_a, raw_name_b, score_name_similarity),
    score_clean_name = map2_dbl(clean_name_a, clean_name_b, score_name_similarity),
    score_type = if_else(type_a == type_b, 1, 0),
    score_domain = map2_dbl(domain_a, domain_b, score_domain_similarity),
    score_position = map2_dbl(pos_a, pos_b, score_position_similarity),
    score_same_iarc_hint = if_else(!is.na(iarc_a) & !is.na(iarc_b) & iarc_a == iarc_b, 1, 0),
    equivalence_score =
      0.30 * score_raw_name +
      0.30 * score_clean_name +
      0.15 * score_type +
      0.15 * score_domain +
      0.05 * score_position +
      0.05 * score_same_iarc_hint,
    evidence = map_chr(equivalence_score, evidence_class),
    confidence = map_chr(equivalence_score, confidence_class)
  ) %>%
  filter(equivalence_score >= 0.45) %>%
  arrange(desc(equivalence_score))

# ------------------------------------------------------------
# 11) diccionario consolidado / crosswalk
# ------------------------------------------------------------
canonical_seed <- data_dictionary_by_sheet %>%
  mutate(
    canonical_candidate = case_when(
      possible_iarc_field == "residencia" & clean_name == "res" ~ "residencia__res",
      possible_iarc_field == "residencia" & clean_name == "deptres" ~ "residencia__deptres",
      possible_iarc_field == "residencia" & clean_name == "provdist" ~ "residencia__provdist",
      possible_iarc_field == "multiple_primary" & clean_name == "pmseq" ~ "multiple_primary__pmseq",
      possible_iarc_field == "multiple_primary" & clean_name == "pmtot" ~ "multiple_primary__pmtot",
      possible_iarc_field == "multiple_primary" & clean_name == "pmcod" ~ "multiple_primary__pmcod",
      !is.na(possible_iarc_field) ~ possible_iarc_field,
      TRUE ~ clean_name
    )
  )

data_dictionary_crosswalk <- canonical_seed %>%
  group_by(canonical_candidate) %>%
  summarise(
    raw_name_variants = paste(sort(unique(raw_name)), collapse = " | "),
    clean_name_variants = paste(sort(unique(clean_name)), collapse = " | "),
    sheets_present = paste(sort(unique(sheet)), collapse = " | "),
    first_year_present = suppressWarnings(min(year_sheet, na.rm = TRUE)),
    last_year_present = suppressWarnings(max(year_sheet, na.rm = TRUE)),
    appears_all_years = n_distinct(year_sheet) == n_distinct(canonical_seed$year_sheet),
    likely_same_field_across_sheets = case_when(
      n_distinct(clean_name) == 1 ~ "yes_direct",
      n_distinct(clean_name) <= 2 ~ "probably_yes",
      TRUE ~ "uncertain"
    ),
    possible_iarc_field = {
      x <- na.omit(possible_iarc_field)
      if (length(x) == 0) NA_character_ else names(sort(table(x), decreasing = TRUE))[1]
    },
    confidence_iarc_mapping = {
      x <- na.omit(confidence_iarc_mapping)
      if (length(x) == 0) "unknown" else names(sort(table(x), decreasing = TRUE))[1]
    },
    harmonization_decision = case_when(
      !is.na(possible_iarc_field) & n_distinct(clean_name) == 1 ~ "candidate_ready_for_harmonization",
      !is.na(possible_iarc_field) & n_distinct(clean_name) > 1 ~ "candidate_needs_review_before_harmonization",
      TRUE ~ "not_iarc_or_uncertain"
    ),
    decision_status = case_when(
      harmonization_decision == "candidate_ready_for_harmonization" ~ "auto_preclassified",
      TRUE ~ "pending_review"
    ),
    notes = case_when(
      appears_all_years ~ "Campo estructuralmente estable en todos los años.",
      TRUE ~ "Campo no estable o con variantes; revisar antes de armonizar."
    ),
    .groups = "drop"
  ) %>%
  arrange(desc(appears_all_years), canonical_candidate)

write_csv(data_dictionary_crosswalk, out_crosswalk, na = "")

# ------------------------------------------------------------
# 12) mapeo preliminar IARC a nivel de variables clave
# ------------------------------------------------------------
iarc_target_fields <- c(
  "sexo",
  "edad",
  "fecha_diagnostico",
  "topografia_icdo",
  "morfologia_icdo",
  "comportamiento",
  "grado",
  "lateralidad",
  "base_diagnostico",
  "estado_vital",
  "fecha_muerte",
  "fecha_ultimo_contacto",
  "residencia",
  "multiple_primary"
)

iarc_mapping_summary <- data_dictionary_by_sheet %>%
  filter(possible_iarc_field %in% iarc_target_fields) %>%
  group_by(possible_iarc_field) %>%
  summarise(
    mapped_raw_names = paste(sort(unique(raw_name)), collapse = " | "),
    mapped_clean_names = paste(sort(unique(clean_name)), collapse = " | "),
    years_present = paste(sort(unique(year_sheet)), collapse = " | "),
    n_years_present = n_distinct(year_sheet),
    confidence_level = names(sort(table(confidence_iarc_mapping), decreasing = TRUE))[1],
    .groups = "drop"
  ) %>%
  right_join(
    tibble(possible_iarc_field = iarc_target_fields),
    by = "possible_iarc_field"
  ) %>%
  mutate(
    field_status = case_when(
      is.na(mapped_raw_names) ~ "not_detected",
      n_years_present == n_distinct(data_dictionary_by_sheet$year_sheet) ~ "detected_all_years",
      TRUE ~ "detected_partial"
    )
  )

# ------------------------------------------------------------
# 13) decision log
# ------------------------------------------------------------
decision_log_auto_equiv <- equivalence_candidates %>%
  filter(
    clean_name_a != clean_name_b |
      raw_name_a != raw_name_b |
      (confidence %in% c("moderate", "low"))
  ) %>%
  transmute(
    variable_or_group = paste0(clean_name_a, " <-> ", clean_name_b),
    issue = "possible_equivalence_across_sheets",
    proposed_decision = paste0("Considerar equivalencia entre '", raw_name_a, "' y '", raw_name_b, "'."),
    rationale = paste0(
      "Similitud por nombre/tipo/dominio/posición. score=",
      round(equivalence_score, 3)
    ),
    evidence = evidence,
    confidence = confidence,
    needs_user_decision = if_else(confidence %in% c("high"), "no", "yes"),
    final_decision = NA_character_,
    date = run_date
  )

decision_log_auto_iarc <- data_dictionary_crosswalk %>%
  filter(!is.na(possible_iarc_field)) %>%
  transmute(
    variable_or_group = canonical_candidate,
    issue = "possible_iarc_mapping",
    proposed_decision = paste0("Mapear provisionalmente a campo IARC: ", possible_iarc_field),
    rationale = paste0(
      "Coincidencia por nombre/variantes estructurales. Estado=",
      harmonization_decision
    ),
    evidence = case_when(
      confidence_iarc_mapping == "high" ~ "evidence_direct",
      confidence_iarc_mapping == "moderate" ~ "inference_probable",
      confidence_iarc_mapping == "low" ~ "hypothesis_uncertain",
      TRUE ~ "weak_signal"
    ),
    confidence = confidence_iarc_mapping,
    needs_user_decision = if_else(
      harmonization_decision == "candidate_ready_for_harmonization",
      "no",
      "yes"
    ),
    final_decision = NA_character_,
    date = run_date
  )

decision_log_missing_critical <- tibble(
  possible_iarc_field = iarc_target_fields
) %>%
  left_join(
    iarc_mapping_summary %>% select(possible_iarc_field, field_status),
    by = "possible_iarc_field"
  ) %>%
  filter(is.na(field_status) | field_status == "not_detected") %>%
  transmute(
    variable_or_group = possible_iarc_field,
    issue = "critical_iarc_field_not_detected",
    proposed_decision = paste0("Confirmar si el campo '", possible_iarc_field, "' no existe o debe reconstruirse/proxy."),
    rationale = "No se detectó una variable candidata clara en la auditoría estructural automática.",
    evidence = "evidence_direct",
    confidence = "high",
    needs_user_decision = "yes",
    final_decision = NA_character_,
    date = run_date
  )

decision_log_header_anomalies <- data_dictionary_by_sheet %>%
  filter(header_anomaly != "none") %>%
  transmute(
    variable_or_group = paste0(sheet, "::", raw_name),
    issue = "header_anomaly_detected",
    proposed_decision = "Revisar si el encabezado corresponde a una variable real, una columna vacía o un desplazamiento estructural del sheet.",
    rationale = paste0("Encabezado clasificado como: ", header_anomaly),
    evidence = "evidence_direct",
    confidence = "high",
    needs_user_decision = "yes",
    final_decision = NA_character_,
    date = run_date
  )

decision_log <- bind_rows(
  decision_log_header_anomalies,
  decision_log_auto_equiv,
  decision_log_auto_iarc,
  decision_log_missing_critical
) %>%
  distinct()

write_csv(decision_log, out_decisionlog, na = "")

# ------------------------------------------------------------
# 13b) dataset armonizado preliminar para análisis epidemiológico
#      - excluye basura estructural
#      - conserva una selección mínima y estable
#      - no resuelve aún codificaciones locales
# ------------------------------------------------------------
vars_keep_crosswalk <- data_dictionary_crosswalk %>%
  mutate(
    keep_for_harmonized = case_when(
      canonical_candidate %in% c(
        "sexo", "edad", "fecha_diagnostico", "topografia_icdo", "morfologia_icdo",
        "comportamiento", "grado", "base_diagnostico", "estado_vital",
        "fecha_muerte", "fecha_ultimo_contacto", "residencia__res",
        "residencia__deptres", "residencia__provdist", "multiple_primary__pmseq",
        "multiple_primary__pmtot", "multiple_primary__pmcod", "lateralidad",
        "cie10", "cicn", "estadio", "dx", "tx", "nx", "mx", "causa"
      ) ~ TRUE,
      TRUE ~ FALSE
    )
  )

harmonized_colmap <- raw_tagged$column_map %>%
  left_join(
    canonical_seed %>%
      select(sheet, col_position, canonical_candidate, possible_iarc_field),
    by = c("sheet", "col_position")
  ) %>%
  left_join(
    variable_quality_profile %>%
      select(sheet, col_position, variable_role, flag_structural_garbage),
    by = c("sheet", "col_position")
  ) %>%
  left_join(
    vars_keep_crosswalk %>%
      select(canonical_candidate, keep_for_harmonized),
    by = "canonical_candidate"
  ) %>%
  mutate(
    keep_for_harmonized = coalesce(keep_for_harmonized, FALSE),
    flag_structural_garbage = coalesce(flag_structural_garbage, FALSE),
    keep_for_harmonized = keep_for_harmonized & !flag_structural_garbage
  )

harmonized_cols <- harmonized_colmap %>%
  filter(keep_for_harmonized) %>%
  select(audit_name, canonical_candidate)

rcpa_harmonized_long <- raw_tagged$data %>%
  mutate(row_id = row_number()) %>%
  pivot_longer(
    cols = -c(row_id, sheet_source, year_sheet),
    names_to = "audit_name",
    values_to = "value"
  ) %>%
  inner_join(harmonized_cols, by = "audit_name") %>%
  mutate(value = na_if(str_trim(as.character(value)), "")) %>%
  filter(!is.na(value)) %>%
  select(row_id, sheet_source, year_sheet, canonical_candidate, value)

saveRDS(rcpa_harmonized_long, out_harmonized)

harmonized_variable_counts <- rcpa_harmonized_long %>%
  count(canonical_candidate, sort = TRUE)

write_csv(harmonized_variable_counts, out_harmonized_counts, na = "")

harmonized_domain_profile <- rcpa_harmonized_long %>%
  count(canonical_candidate, value, sort = TRUE) %>%
  group_by(canonical_candidate) %>%
  mutate(
    n_total_variable = sum(n),
    pct_within_variable = round(100 * n / n_total_variable, 4),
    rank_within_variable = row_number()
  ) %>%
  ungroup()

write_csv(harmonized_domain_profile, out_harmonized_codebook, na = "")

# ------------------------------------------------------------
# 14) audit log json
# ------------------------------------------------------------
variables_all_years <- variable_presence_by_year %>%
  filter(appears_all_years) %>%
  pull(clean_name)

variables_year_specific <- variable_presence_by_year %>%
  filter(consistency_structural == "sporadic_or_year_specific") %>%
  pull(clean_name)

structural_changes <- presence_long %>%
  distinct(year_sheet, clean_name) %>%
  group_by(year_sheet) %>%
  summarise(n_variables = n(), .groups = "drop") %>%
  arrange(year_sheet) %>%
  mutate(
    diff_vs_previous = n_variables - lag(n_variables)
  )

audit_log <- list(
  metadata = list(
    source_file = path_xlsx,
    created_at = as.character(Sys.time()),
    run_date = run_date,
    n_sheets = length(sheets),
    sheets = sheets
  ),
  sheet_summary = map(
    sheets,
    function(sh) {
      df <- raw_sheets[[sh]]
      list(
        sheet = sh,
        year_sheet = safe_parse_year(sh),
        n_rows = nrow(df),
        n_cols = ncol(df),
        raw_names = names(df)
      )
    }
  ),
  global_summary = list(
    n_rows_raw_exact = nrow(raw_exact),
    n_cols_raw_exact = ncol(raw_exact),
    n_unique_clean_names = n_distinct(data_dictionary_by_sheet$clean_name),
    variables_present_all_years = variables_all_years,
    variables_year_specific = variables_year_specific
  ),
  structural_changes_between_years = structural_changes,
  iarc_mapping_summary = iarc_mapping_summary,
  critical_missing_iarc_fields = iarc_mapping_summary %>%
    filter(is.na(field_status) | field_status == "not_detected") %>%
    pull(possible_iarc_field),
  flagged_suspicious_headers = data_dictionary_by_sheet %>%
    filter(header_anomaly != "none") %>%
    select(sheet, raw_name, clean_name, col_position, header_anomaly),
  notes = list(
    conservative_policy = "No se asumieron equivalencias automáticas como definitivas.",
    evidence_levels = c("evidence_direct", "inference_probable", "hypothesis_uncertain"),
    next_step = "Revisión humana del decision_log antes de armonización epidemiológica."
  )
)

write_json(
  audit_log,
  path = out_audit_json,
  pretty = TRUE,
  auto_unbox = TRUE,
  na = "null"
)

# ------------------------------------------------------------
# 15) outputs para anexos
# ------------------------------------------------------------
annex_dataset_structure <- data_dictionary_by_sheet %>%
  select(
    sheet, year_sheet, col_position, raw_name, clean_name, raw_type_guess,
    n_rows, n_non_missing, pct_missing, n_unique
  )

annex_variable_dictionary <- data_dictionary_by_sheet %>%
  left_join(
    variable_quality_profile %>%
      select(sheet, col_position, variable_role, flag_structural_garbage),
    by = c("sheet", "col_position")
  ) %>%
  select(
    sheet, year_sheet, raw_name, clean_name,
    possible_meaning, possible_iarc_field, confidence_iarc_mapping,
    variable_role, flag_structural_garbage, notes
  )

annex_variable_presence_matrix <- presence_matrix

write_csv(annex_dataset_structure, out_annex_structure, na = "")
write_csv(annex_variable_dictionary, out_annex_dict, na = "")
write_csv(annex_variable_presence_matrix, out_annex_presence, na = "")

# ------------------------------------------------------------
# 16) mensajes finales
# ------------------------------------------------------------
cat("\n============================================\n")
cat("AUDITORÍA RAW COMPLETADA\n")
cat("============================================\n")
cat(glue("Excel fuente: {path_xlsx}\n"))
cat(glue("Hojas leídas: {length(sheets)} -> {paste(sheets, collapse = ', ')}\n"))
cat(glue("raw_exact  : {out_raw_exact}\n"))
cat(glue("raw_tagged : {out_raw_tagged}\n"))
cat(glue("dict_sheet : {out_dict_sheet}\n"))
cat(glue("var_quality: {out_var_quality}\n"))
cat(glue("presence   : {out_presence}\n"))
cat(glue("crosswalk  : {out_crosswalk}\n"))
cat(glue("decisionlog: {out_decisionlog}\n"))
cat(glue("audit_json : {out_audit_json}
"))
cat(glue("harmonized : {out_harmonized}
"))
cat(glue("harm_counts : {out_harmonized_counts}
"))
cat(glue("harm_codebk: {out_harmonized_codebook}
"))
cat("============================================\n\n")
